# reporter: "xcode"

included:
  - GhibliApp
excluded:
  - GhibliApp/Resources

analyzer_rules:
  - unused_import

disabled_rules:
  - superfluous_disable_command
  # - instance_property
  # - file_types_order
  # - type_contents_order

opt_in_rules:
  # - type_contents_order
  # - file_types_order
  # - explicit_acl
  - weak_delegate
  - mark
  - private_outlet
  - opening_brace
  - vertical_whitespace
  # - vertical_whitespace_opening_braces
  # - vertical_whitespace_closing_braces
  - vertical_whitespace_between_cases
  - leading_whitespace
  - trailing_whitespace
  - closing_brace
  - closure_spacing
  - comma
  - file_name_no_space
  - no_space_in_method_call
  - operator_usage_whitespace
  - operator_whitespace
  - return_arrow_whitespace
  - yoda_condition
  - unneeded_break_in_switch
  - trailing_semicolon
  - syntactic_sugar
  - sorted_imports
  - statement_position
  - sorted_first_last
  - redundant_type_annotation
  - redundant_set_access_control
  - redundant_optional_initialization
  - redundant_nil_coalescing
  - redundant_discardable_let
  - reduce_boolean
  - private_over_fileprivate
  - prefixed_toplevel_constant
  - multiple_closures_with_trailing_closure
  - multiline_parameters_brackets
  - multiline_literal_brackets
  - multiline_function_chains
  - multiline_arguments
  - multiline_arguments_brackets
  - modifier_order
  - large_tuple
  - last_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicitly_unwrapped_optional
  - force_try
  - force_cast
  - for_where
  - block_based_kvo
  - implicit_return
  - protocol_property_accessors_order
  - class_delegate_protocol
  - compiler_protocol_init
  - trailing_comma

line_length:
 warning: 150
 error: 150

private_outlet:
 severity: error

mark:
 severity: error

vertical_whitespace:
  severity: error
  max_empty_lines: 1 # Exige pelo menos uma linha em branco no início da classe

type_name:
 max_length: 60

identifier_name:
 min_length: 3
 excluded:
   - id
   - at
   - by
   - to
   - y
   - x

function_parameter_count:
  warning: 6

multiline_arguments:
  first_argument_location: next_line

trailing_comma:
  mandatory_comma: true

modifier_order:
  preferred_modifier_order: 
    - acl
    - override
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

custom_rules:
  final_class:
    name: "Final Class"
    regex: "(^[ ]*class [A-Z]+)"
    message: "Class should be marked as final."
    severity: warning

  if_as_guard:
    included: ".*.swift"
    regex: '(?<=\n) *if [^\{]+\{\s*return\s*(?:nil){0,1}([^a-zA-z\n]*)\n*\s*\}(?! *else)'
    name: "If as Guard"
    message: "Don't use an if statement to just return – use guard for such cases instead."
    severity: warning

  late_force_unwrapping:
    included: ".*.swift"
    regex: '\(\S+\?\.\S+\)!'
    name: "Late Force Unwrapping"
    message: "Don't use ? first to force unwrap later – directly unwrap within the parantheses."
    severity: warning
  
  local_l10n:
    included: ".*.swift"
    regex: 'func \S+\s*\{\s*[^\}]*let l10n'
    name: "Local l10n"
    message: "Don't name local variable `l10n` – use a property instead and further specify with `localL10n` if needed."
    severity: warning

  single_line_enum_cases:
    included: ".*.swift"
    regex: 'enum [^\{]+\{\s*(?:\s*\/\/[^\n]*)*\s*case\s+[^,(\n]+,'
    name: "Single Line Enum Cases"
    message: "Use a new line for each enum case."
    severity: warning

  single_line_guard:
    included: ".*.swift"
    regex: 'guard[^\{]{2,80}else\s*\{\s*\n\s*return.{2,40}\}'
    name: "Single Line Guard"
    message: "Use a single line guard for simple checks."
    severity: warning

  singleton_default_private_init:
    included: ".*.swift"
    regex: 'class +(?<TYPE>\w+)(?:<[^\>]+>)? *\{.*static let `default`(?:: *\k<TYPE>)? *= *\k<TYPE>\(.*(?<=private) init\('
    name: "Singleton Default Private Init"
    message: "Singletons with a `default` object (pseudo-singletons) should not declare init methods as private."
    severity: warning

  singleton_shared_final:
    included: ".*.swift"
    regex: '(?<!final )class +(?<TYPE>\w+)(?:<[^\>]+>)? *\{.*static let shared(?:: *\k<TYPE>)? *= *\k<TYPE>\('
    name: "Singleton Shared Final"
    message: "Singletons with a single object (`shared`) should be marked as final."
    severity: warning

  empty_type:
    included: ".*.swift"
    regex: '(?:class|protocol|struct|enum) [^\{]+\{\s*\}'
    name: "Empty Type"
    message: "Don't keep empty types in code without commenting inside why they are needed or a `// TODO: not yet implemented`."
    severity: warning

  class_protocol:
    regex: ': class'
    message: "Use Anyobject instead"

  # newline_after_definition_start:
  #   name: "There should be an empty line after the definition opening braces"
  #   regex: '(^[ a-zA-Z]*(?:protocol|extension|class|struct|enum)[ a-zA-Z:,<>\n_]*\{\n *\S+)'
  #   severity: warning

  # newline_before_definition_end:
  #   name: "There should be an empty line before the definition closing braces"
  #   regex: '^[^\n]+\n\}\n'
  #   severity: warning